In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot
print(np.__version__)
#from sklearn.metrics import ConfusionMatrixDisplay
#import seaborn

1.26.4

In [2]:
ML_folder = '../../data_in/ML_catalogs/'
fn_ML = ML_folder + '4FGL-DR4_v34_cov_shift_vs_prior_shift_prediction.csv'
list_fn = '../../data_in/GU_lists/list_bright_GUs.csv'
fn_out = '../../data_in/GU_lists/list_bright_GUs_ML_classes.csv'

In [3]:
ML_df = pd.read_csv(fn_ML, index_col=0)
GU_df = pd.read_csv(list_fn, index_col=0)

In [4]:
GU_df = pd.read_csv(list_fn)

In [5]:
names = [name for name in GU_df.index if name in ML_df.index]
names_na = [name for name in GU_df.index if name not in names]

In [6]:
add_cols = ['RF_class', 'PDF_class', 'Gauss_PDF']
for col in add_cols:
    GU_df.loc[names, col] = ML_df.loc[names, col]
    if col.find('class') > -1:
        GU_df.loc[names_na, col] = 'na'
    else:
        GU_df.loc[names_na, col] = 0.

In [7]:
GU_df

,NAME,RAJ2000,DEJ2000,LON,LAT,RF_class,PDF_class,Gauss_PDF
0,4FGL J0034.6+6438,8.6619,64.6393,121.1340,1.826170,na,na,0.0
1,4FGL J0057.9+6326,14.4955,63.4385,123.6630,0.576046,na,na,0.0
2,4FGL J0204.7+6656,31.1953,66.9372,130.0390,5.082900,na,na,0.0
3,4FGL J0235.3+5650,38.8479,56.8478,136.8190,-3.194750,na,na,0.0
4,4FGL J0616.5+2235,94.1441,22.5943,188.9620,2.905250,na,na,0.0
...,...,...,...,...,...,...,...,...
155,4FGL J2114.3+5023,318.5900,50.3993,91.7634,1.148750,na,na,0.0
156,4FGL J2116.2+3701,319.0590,37.0257,82.3045,-8.341010,na,na,0.0
157,4FGL J2117.9+3729,319.4920,37.4842,82.8801,-8.273970,na,na,0.0
158,4FGL J2218.8+4736,334.7240,47.6008,98.0812,-7.775450,na,na,0.0
159,4FGL J2220.8+6319,335.2240,63.3185,106.9500,5.218630,na,na,0.0

In [8]:
save_results = True
if save_results:
    print('Save the result to file:')
    print(fn_out)
    GU_df.to_csv(fn_out)

Save the result to file:
../../data_in/GU_lists/list_bright_GUs_ML_classes.csv

In [9]:
GU_df.loc[names_na]

,NAME,RAJ2000,DEJ2000,LON,LAT,RF_class,PDF_class,Gauss_PDF
0,4FGL J0034.6+6438,8.6619,64.6393,121.1340,1.826170,na,na,0.0
1,4FGL J0057.9+6326,14.4955,63.4385,123.6630,0.576046,na,na,0.0
2,4FGL J0204.7+6656,31.1953,66.9372,130.0390,5.082900,na,na,0.0
3,4FGL J0235.3+5650,38.8479,56.8478,136.8190,-3.194750,na,na,0.0
4,4FGL J0616.5+2235,94.1441,22.5943,188.9620,2.905250,na,na,0.0
...,...,...,...,...,...,...,...,...
155,4FGL J2114.3+5023,318.5900,50.3993,91.7634,1.148750,na,na,0.0
156,4FGL J2116.2+3701,319.0590,37.0257,82.3045,-8.341010,na,na,0.0
157,4FGL J2117.9+3729,319.4920,37.4842,82.8801,-8.273970,na,na,0.0
158,4FGL J2218.8+4736,334.7240,47.6008,98.0812,-7.775450,na,na,0.0
159,4FGL J2220.8+6319,335.2240,63.3185,106.9500,5.218630,na,na,0.0

In [10]:
print('Number of bright GU sources: %i' % len(GU_df))
classes = ['bll+', 'fsrq+', 'psr+', 'msp+', 'Gauss']
print('PDF predictions')
for cl in classes:
    print('\t%s candidates: %i' % (cl, sum(GU_df['PDF_class'] == cl)))
print('Fraction of Gaussian candidates: %.3f' % (sum(GU_df['PDF_class'] == 'Gauss')/len(GU_df)))
classes = ['bll+', 'fsrq+', 'psr+', 'msp+']
print('\nRF predictions')
for cl in classes:
    print('\t%s candidates: %i' % (cl, sum(GU_df['RF_class'] == cl)))

Number of bright GU sources: 160
PDF predictions
	bll+ candidates: 0
	fsrq+ candidates: 0
	psr+ candidates: 0
	msp+ candidates: 0
	Gauss candidates: 0
Fraction of Gaussian candidates: 0.000

RF predictions
	bll+ candidates: 0
	fsrq+ candidates: 0
	psr+ candidates: 0
	msp+ candidates: 0